# Generated by Django 4.1.13 on 2024-04-22 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('biology', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('released', models.DateTimeField()),
                ('overview', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.TextField()),
                ('genre', models.CharField(max_length=200)),
                ('casts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cast')),
            ],
        ),
    ]
