# Generated by Django 4.1.13 on 2024-04-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='biology',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='casts',
        ),
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(to='main.cast'),
        ),
    ]
